import { UserRole } from '@/lib/types';

export type Permission =
  | 'REPORTS_VIEW'
  | 'LOGISTICS_VIEW'
  | 'TRIP_CREATE'
  | 'TRIP_EDIT_ACTIVE_FY'
  | 'TRIP_RESTORE_DELETED'
  | 'TRIP_SETTLED_EDIT'
  | 'PAYMENT_RECORD'
  | 'PAYMENT_BACKDATE_30D'
  | 'PAYMENT_BACKDATE_UNLIMITED'
  | 'PAYMENT_REVERSE'
  | 'EXPENSE_RECORD'
  | 'BILL_GENERATE'
  | 'BILL_CANCEL_RESTORE'
  | 'USER_MANAGEMENT'
  | 'AUDIT_VIEW';

export const PERMISSION_MATRIX: Record<Permission, UserRole[]> = {
  REPORTS_VIEW: ['SUPER_ADMIN', 'OPERATOR', 'CA_AUDITOR'],
  LOGISTICS_VIEW: ['SUPER_ADMIN', 'OPERATOR', 'CA_AUDITOR'],
  TRIP_CREATE: ['SUPER_ADMIN', 'OPERATOR'],
  TRIP_EDIT_ACTIVE_FY: ['SUPER_ADMIN', 'OPERATOR'],
  TRIP_RESTORE_DELETED: ['SUPER_ADMIN'],
  TRIP_SETTLED_EDIT: ['SUPER_ADMIN'],
  PAYMENT_RECORD: ['SUPER_ADMIN', 'OPERATOR'],
  PAYMENT_BACKDATE_30D: ['SUPER_ADMIN', 'OPERATOR'],
  PAYMENT_BACKDATE_UNLIMITED: ['SUPER_ADMIN'],
  PAYMENT_REVERSE: ['SUPER_ADMIN'],
  EXPENSE_RECORD: ['SUPER_ADMIN', 'OPERATOR'],
  BILL_GENERATE: ['SUPER_ADMIN', 'OPERATOR'],
  BILL_CANCEL_RESTORE: ['SUPER_ADMIN'],
  USER_MANAGEMENT: ['SUPER_ADMIN'],
  AUDIT_VIEW: ['SUPER_ADMIN', 'OPERATOR', 'CA_AUDITOR'],
};

export function isPermissionGranted(role: UserRole, permission: Permission): boolean {
  const allowedRoles = PERMISSION_MATRIX[permission];
  return allowedRoles ? allowedRoles.includes(role) : false;
}
