import React from 'react';
import { Trip } from '../../../features/trips/trips.types';

interface BillSummaryProps {
  selectedTrips: Trip[];
  billingType: 'INDIVIDUAL' | 'CONSOLIDATED';
}

export const BillSummary: React.FC<BillSummaryProps> = ({ selectedTrips, billingType }) => {
  const tripCount = selectedTrips.length;
  // Note: This is strictly a frontend estimation for UX preview. 
  // The authoritative total is calculated by the backend during generation.
  const estimatedTotal = selectedTrips.reduce((sum, trip) => sum + Number(trip.customer_balance || 0), 0);

  return (
    <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-100 dark:border-blue-800 mb-6">
      <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-3 uppercase tracking-wider">Preview Summary</h3>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div>
          <p className="text-xs text-blue-700 dark:text-blue-300">Billing Mode</p>
          <p className="font-medium text-blue-900 dark:text-blue-100">{billingType}</p>
        </div>
        <div>
          <p className="text-xs text-blue-700 dark:text-blue-300">Selected Trips</p>
          <p className="font-medium text-blue-900 dark:text-blue-100">{tripCount}</p>
        </div>
        <div>
          <p className="text-xs text-blue-700 dark:text-blue-300">Estimated Total</p>
          <p className="font-bold text-blue-900 dark:text-blue-100">₹{estimatedTotal.toFixed(2)}</p>
        </div>
      </div>
      <p className="text-xs text-blue-600 dark:text-blue-400 mt-3 flex items-center">
        * Final accounting total will be verified and generated by the authoritative backend engine.
      </p>
    </div>
  );
};
