import React from 'react';
import { Link } from 'react-router-dom';
import { ROUTES } from '../../constants';
import { FileText, Users, Truck, DollarSign, AlertCircle, TrendingUp, Briefcase } from 'lucide-react';

const ReportCard: React.FC<{ title: string; description: string; path: string; icon: React.ReactNode }> = ({ title, description, path, icon }) => (
  <Link to={path} className="block p-6 bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 hover:border-blue-500 transition-colors group">
    <div className="flex items-start gap-4">
      <div className="p-3 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg group-hover:bg-blue-100 transition-colors">
        {icon}
      </div>
      <div>
        <h3 className="font-semibold text-gray-900 dark:text-white text-lg">{title}</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{description}</p>
      </div>
    </div>
  </Link>
);

export const ReportsPage: React.FC = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Reports Hub</h1>
        <p className="text-gray-500 dark:text-gray-400">Access authoritative financial and operational reports generated by the backend engine.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <ReportCard 
          title="Monthly Trip Register" 
          description="Detailed breakdown of all trips executed in a specific month." 
          path={`${ROUTES.PROTECTED.REPORTS}/monthly-trip-register`}
          icon={<Truck size={24} />}
        />
        
        <ReportCard 
          title="Party Ledger" 
          description="Comprehensive statement of account for a specific customer." 
          path={`${ROUTES.PROTECTED.REPORTS}/party-ledger`}
          icon={<Users size={24} />}
        />
        
        <ReportCard 
          title="Vehicle Owner Ledger" 
          description="Comprehensive statement of account for a specific vehicle owner." 
          path={`${ROUTES.PROTECTED.REPORTS}/vehicle-owner-ledger`}
          icon={<Briefcase size={24} />}
        />
        
        <ReportCard 
          title="Outstanding Report" 
          description="Current outstanding balances across all parties." 
          path={`${ROUTES.PROTECTED.REPORTS}/outstanding`}
          icon={<DollarSign size={24} />}
        />
        
        <ReportCard 
          title="Pending POD Report" 
          description="List of all trips lacking complete proof of delivery documentation." 
          path={`${ROUTES.PROTECTED.REPORTS}/pending-pod`}
          icon={<AlertCircle size={24} />}
        />
        
        <ReportCard 
          title="Financial Summary" 
          description="High-level revenue and expense summaries for a given period." 
          path={`${ROUTES.PROTECTED.REPORTS}/financial-summary`}
          icon={<FileText size={24} />}
        />
        
        <ReportCard 
          title="Profit Summary" 
          description="Detailed profitability analysis of operations." 
          path={`${ROUTES.PROTECTED.REPORTS}/profit-summary`}
          icon={<TrendingUp size={24} />}
        />
      </div>
    </div>
  );
};
